-- Tabla principal: usuarios (credenciales y rol del sistema)
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nombres VARCHAR(255),
    apellidos VARCHAR(255),
    rol VARCHAR(255)
);

-- Tabla catalogo: roles del sistema
CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE
);

-- Datos iniciales: roles en orden fijo (el id_rol resultante es el que usa @PreAuthorize en el resto de microservicios)
INSERT INTO roles (nombre) VALUES
    ('Jefatura'),   -- id_rol = 1
    ('Secretaria'), -- id_rol = 2
    ('Naviero'),    -- id_rol = 3
    ('Finanzas');   -- id_rol = 4

-- Tabla catalogo: permisos del sistema
CREATE TABLE permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- Tabla puente: permisos asignados a cada rol
CREATE TABLE roles_permisos (
    id_rol_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL REFERENCES roles(id_rol),
    id_permiso INTEGER NOT NULL REFERENCES permisos(id_permiso)
);

-- Tabla refresh_tokens: tokens de refresco de sesion (JWT)
CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    token VARCHAR(512) NOT NULL UNIQUE,
    expiry_date TIMESTAMPTZ NOT NULL
);
