-- Tabla catalogo: tipos_documento
CREATE TABLE tipos_documento (
    id_tipo_doc INTEGER PRIMARY KEY,
    siglas VARCHAR(10) NOT NULL,
    descripcion VARCHAR(100)
);

-- Datos iniciales de ejemplo (ajusta segun lo que ya tengas en Supabase)
INSERT INTO tipos_documento (id_tipo_doc, siglas, descripcion) VALUES
    (1, 'DNI', 'Documento Nacional de Identidad'),
    (2, 'CE', 'Carne de Extranjeria'),
    (3, 'PAS', 'Pasaporte');

-- Tabla principal: socios
CREATE TABLE socios (
    id_socio BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_tipo_doc INTEGER NOT NULL REFERENCES tipos_documento(id_tipo_doc),
    dni VARCHAR(20) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    estado_membresia VARCHAR(30),
    fecha_ingreso DATE,
    clasificacion TEXT,
    correo TEXT
);

-- Tabla solicitudes: solicitudes de inscripcion de nuevos socios (Secretaria crea, Jefatura evalua)
CREATE TABLE solicitudes (
    id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio BIGINT NOT NULL REFERENCES socios(id_socio),
    tipo_solicitud VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    fecha_resolucion TIMESTAMP,
    observacion VARCHAR(255),
    usuario_revisor VARCHAR(255)
);

-- Tabla solicitudes_retiro: solicitudes de baja de socios (requiere no tener deuda pendiente)
CREATE TABLE solicitudes_retiro (
    id_solicitud BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_socio BIGINT NOT NULL REFERENCES socios(id_socio),
    motivo VARCHAR(255),
    estado_solicitud VARCHAR(255) NOT NULL,
    fecha_solicitud TIMESTAMP NOT NULL,
    fecha_procesamiento TIMESTAMP,
    usuario_atencion VARCHAR(255)
);
