apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\7MO CICLO\DSW\Club-Nautico\club-nautico-microservicios\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\7MO CICLO\DSW\Club-Nautico\club-nautico-microservicios\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: auth-service-config
          image: club-nautico-microservicios-auth-service:latest
          imagePullPolicy: IfNotPresent
          name: club-nautico-auth-service
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
