apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-facturacion-config
  namespace: default
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SERVER_PORT: "8084"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_PASSWORD: "ClubNautico2026!"
  SPRING_DATASOURCE_URL: "jdbc:sqlserver://sqlserver-facturacion:1433;databaseName=facturacionDb;encrypt=true;trustServerCertificate=true"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
