apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\7MO CICLO\DSW\Club-Nautico\club-nautico-microservicios\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: ms-nautica
  name: ms-nautica
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ms-nautica
  template:
    metadata:
      annotations:
        kompose.cmd: C:\7MO CICLO\DSW\Club-Nautico\club-nautico-microservicios\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: ms-nautica
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: club-nautico-ms-nautica--env
          image: club-nautico-microservicios-ms-nautica:latest
          imagePullPolicy: Never
          name: club-nautico-ms-nautica
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
