apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-socios-config
  namespace: default
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SERVER_PORT: "8082"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-socios:5434/sociosDb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
