<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>club.ms</groupId>
    <artifactId>ClubNauticoContainer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <name>ClubNauticoContainer</name>
    <packaging>pom</packaging>
    <description>Proyecto agregador: compila todos los microservicios Spring del Club Nautico con un solo comando</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>21</maven.compiler.release>
    </properties>

    <dependencyManagement>
        <dependencies>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
            <plugins>
            </plugins>
        </pluginManagement>
    </build>

    <modules>
        <module>club.ms.config</module>
        <module>club.ms.eureka</module>
        <module>ClubNauticoMSSocios</module>
        <!-- <module>ms-facturacion</module> -->
        <!-- <module>auth-service</module> -->
    </modules>
</project>
