version: '3.8'

services:
  # 1. Nuestro contenedor de Base de Datos
  db-nautica:
    image: mysql:8.0
    container_name: mysql-nautica-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: club_nautica_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Esto evita que los datos se borren si el contenedor se apaga

  # 2. Nuestro contenedor de Node.js (Microservicio)
  api-nautica:
    build: .
    container_name: api-nautica
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DB_HOST=db-nautica # ¡Ojo aquí! Ya no es localhost, ahora Node busca al contenedor de la BD por su nombre
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=club_nautica_db
      - JWT_SECRET=tu_secreto_compartido_aqui
    depends_on:
      - db-nautica

volumes:
  db_data: